// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADigk1PH6LBs0QMV-Zu_vwid09vQ99Jv0',
    appId: '1:425044932718:web:f20db3fd281b91d4574e7f',
    messagingSenderId: '425044932718',
    projectId: 'recipe-app-81189',
    authDomain: 'recipe-app-81189.firebaseapp.com',
    storageBucket: 'recipe-app-81189.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_6nWR-U6-6MWINqd8HXSrSRUt47TNhQ',
    appId: '1:425044932718:android:bb971ca28be4f253574e7f',
    messagingSenderId: '425044932718',
    projectId: 'recipe-app-81189',
    storageBucket: 'recipe-app-81189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBml93twkggpwPk_9kYE-3vGoAFyBNlC9g',
    appId: '1:425044932718:ios:61568f968b5d40a2574e7f',
    messagingSenderId: '425044932718',
    projectId: 'recipe-app-81189',
    storageBucket: 'recipe-app-81189.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBml93twkggpwPk_9kYE-3vGoAFyBNlC9g',
    appId: '1:425044932718:ios:61568f968b5d40a2574e7f',
    messagingSenderId: '425044932718',
    projectId: 'recipe-app-81189',
    storageBucket: 'recipe-app-81189.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADigk1PH6LBs0QMV-Zu_vwid09vQ99Jv0',
    appId: '1:425044932718:web:f951e043d2170e77574e7f',
    messagingSenderId: '425044932718',
    projectId: 'recipe-app-81189',
    authDomain: 'recipe-app-81189.firebaseapp.com',
    storageBucket: 'recipe-app-81189.firebasestorage.app',
  );
}
